### ISSUE TITLE
copyFiles file-loader

### ISSUE THREAD

**Issue by dreadnip** [sumocoders/FrameworkStylePackage#37]
When installing a new project, the webpack-config.js contains a snippet
`.copyFiles(
    {
      from: './assets/images',
      to: 'images/[path][name].[hash:8].[ext]'
    }
  )`
which throws an error when you first run npm install:
`Error: Install file-loader to use copyFiles()`

Running `npm install file-loader --save-dev` solves this issue. Could be included in the base package.json?

**Comment by tijsverkoyen** [comment]
This was resolved in https://github.com/sumocoders/FrameworkStylePackage/commit/d47cc57defde5f81c9696762540967ecbeef3605
